-- Enable Row Level Security
alter table supabase.students enable row level security;

-- Create students table
create table if not exists public.students (
    id uuid not null primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone,
    full_name text,
    phone_number text,
    email text,
    registration_number text
);

-- Create attendance table
create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    session_id uuid not null,
    student_id uuid not null,
    latitude double precision,
    longitude double precision,
    qr_id text,
    scan_timestamp timestamp with time zone
);

-- Create sessions table
create table if not exists public.sessions (
    id uuid not null default gen_random_uuid() primary key,
    created_at timestamp with time zone not null default now(),
    teacher_id uuid not null,
    is_active boolean default true,
    expires_at timestamp with time zone
);

-- Create function to submit attendance
create or replace function submit_attendance(
    p_session_id uuid,
    p_student_id uuid,
    p_latitude double precision,
    p_longitude double precision,
    p_qr_id text,
    p_scan_timestamp timestamp with time zone,
    p_full_name text,
    p_email text
)
returns table(success boolean, message text) as $$
declare
    v_session_exists boolean;
    v_already_submitted boolean;
    v_session_expires_at timestamp with time zone;
begin
    -- 1. Check if the session is valid and active
    select exists(select 1 from public.sessions where id = p_session_id and is_active = true and expires_at > now()) into v_session_exists;
    
    if not v_session_exists then
        return query select false, 'Invalid or expired session. Please scan a new QR code.';
    end if;

    -- 2. Check if the student has already submitted for this session
    select exists(select 1 from public.attendance where session_id = p_session_id and student_id = p_student_id) into v_already_submitted;

    if v_already_submitted then
        return query select false, 'You have already marked your attendance for this session.';
    end if;

    -- 3. Insert the attendance record
    begin
        insert into public.attendance (session_id, student_id, latitude, longitude, qr_id, scan_timestamp)
        values (p_session_id, p_student_id, p_latitude, p_longitude, p_qr_id, p_scan_timestamp);
    exception when others then
        return query select false, 'Failed to record attendance. Please try again.';
    end;

    -- 4. If everything is successful
    return query select true, 'Attendance marked successfully for ' || p_full_name || '!';

end;
$$ language plpgsql;

-- Set up Policies for RLS
-- Students can only view and update their own profile.
drop policy if exists "Allow individual access" on public.students;
create policy "Allow individual access"
on public.students for all
using (auth.uid() = id);

-- Allow authenticated users to insert into attendance table
drop policy if exists "Allow authenticated insert" on public.attendance;
create policy "Allow authenticated insert"
on public.attendance for insert
to authenticated
with check (true);

-- Allow authenticated users to view their own attendance
drop policy if exists "Allow individual select" on public.attendance;
create policy "Allow individual select"
on public.attendance for select
using (auth.uid() = student_id);

-- Sessions are publically viewable if active
drop policy if exists "Allow active session select" on public.sessions;
create policy "Allow active session select"
on public.sessions for select
using (is_active = true);
