
// This file is automatically generated. Do not modify it manually.
// You can update the configuration by running the "Update Firebase project" command.
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  projectId: 'studio-180803141-4a9f7',
  appId: '1:810763986999:web:dca0ac01c4730e7a38f7b2',
  apiKey: 'AIzaSyDXv2n7X88B6ahdvAFCwDd7bZ6fHb0x0lE',
  authDomain: 'studio-180803141-4a9f7.firebaseapp.com',
  storageBucket: 'studio-180803141-4a9f7.appspot.com',
  messagingSenderId: '810763986999',
};
